spring:
  cache:
    type: redis
  redis:
    port: 6379
    host: 127.0.0.1
    database: 5
    # password: admin
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot?useSSL=false
    username: root
    password: root
    hikari:
      connection-test-query: select 1
      validation-timeout: 50000
      idle-timeout: 600000
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 30000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      max-lifetime: 1800000
      # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximumPoolSize: 60
      #
      minimum-idle: 10
      # 连接只读数据库时配置为true， 保证安全
      read-only: false

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: true
    open-in-view: false


mybatis:
  configuration:
    # 全局映射器启用缓存
    cache-enabled: true
    # 按需加载字段(加载字段由SQL指定),不会加载关联表的所有字段,以提高性能
    aggressive-lazy-loading: false
    # 查询时,关闭关联对象及时加载以提高性能
    lazy-loading-enabled: false
    #对于批量更新操作缓存SQL以提高性能
    default-executor-type: reuse
    #允许返回不同的结果集以达到通用的效果
    multiple-result-sets-enabled: true
    #数据库执行超时时间
    default-statement-timeout: 25000
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.andy.entity
